// This file is auto-generated by @hey-api/openapi-ts

/**
 * 對話響應模式
 */
export type ChatResponse = {
    id: string;
    title: string;
    created_at: string;
    updated_at: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type HealthResponse = {
    status: boolean;
};

/**
 * 建立新知識項的請求模式
 */
export type KnowledgeCreate = {
    title: string;
    content: string;
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * 知識項響應模式
 */
export type KnowledgeResponse = {
    id: string;
    title: string;
    content: string;
    metadata: {
        [key: string]: unknown;
    };
    created_at: string;
    updated_at: string;
};

/**
 * 更新知識項的請求模式
 */
export type KnowledgeUpdate = {
    title?: string | null;
    content?: string | null;
    metadata?: {
        [key: string]: unknown;
    } | null;
};

/**
 * 建立新訊息的請求模式
 */
export type MessageCreate = {
    content: string;
};

/**
 * 訊息響應模式
 */
export type MessageResponse = {
    content: string;
    role: string;
};

export type RootResponse = {
    message?: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type CreateChatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chat';
};

export type CreateChatResponses = {
    /**
     * Successful Response
     */
    201: ChatResponse;
};

export type CreateChatResponse = CreateChatResponses[keyof CreateChatResponses];

export type GetChatMessagesData = {
    body?: never;
    path: {
        chat_id: string;
    };
    query?: never;
    url: '/chat/{chat_id}/messages';
};

export type GetChatMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChatMessagesError = GetChatMessagesErrors[keyof GetChatMessagesErrors];

export type GetChatMessagesResponses = {
    /**
     * Successful Response
     */
    200: Array<MessageResponse>;
};

export type GetChatMessagesResponse = GetChatMessagesResponses[keyof GetChatMessagesResponses];

export type CreateMessageData = {
    body: MessageCreate;
    path: {
        chat_id: string;
    };
    query?: never;
    url: '/chat/{chat_id}/messages';
};

export type CreateMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateMessageError = CreateMessageErrors[keyof CreateMessageErrors];

export type CreateMessageResponses = {
    /**
     * Successful Response
     */
    201: MessageResponse;
};

export type CreateMessageResponse = CreateMessageResponses[keyof CreateMessageResponses];

export type GetAllKnowledgeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/knowledge';
};

export type GetAllKnowledgeResponses = {
    /**
     * Successful Response
     */
    200: Array<KnowledgeResponse>;
};

export type GetAllKnowledgeResponse = GetAllKnowledgeResponses[keyof GetAllKnowledgeResponses];

export type CreateKnowledgeData = {
    body: KnowledgeCreate;
    path?: never;
    query?: never;
    url: '/knowledge';
};

export type CreateKnowledgeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateKnowledgeError = CreateKnowledgeErrors[keyof CreateKnowledgeErrors];

export type CreateKnowledgeResponses = {
    /**
     * Successful Response
     */
    201: KnowledgeResponse;
};

export type CreateKnowledgeResponse = CreateKnowledgeResponses[keyof CreateKnowledgeResponses];

export type DeleteKnowledgeData = {
    body?: never;
    path: {
        knowledge_id: string;
    };
    query?: never;
    url: '/knowledge/{knowledge_id}';
};

export type DeleteKnowledgeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteKnowledgeError = DeleteKnowledgeErrors[keyof DeleteKnowledgeErrors];

export type DeleteKnowledgeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteKnowledgeResponse = DeleteKnowledgeResponses[keyof DeleteKnowledgeResponses];

export type UpdateKnowledgeData = {
    body: KnowledgeUpdate;
    path: {
        knowledge_id: string;
    };
    query?: never;
    url: '/knowledge/{knowledge_id}';
};

export type UpdateKnowledgeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateKnowledgeError = UpdateKnowledgeErrors[keyof UpdateKnowledgeErrors];

export type UpdateKnowledgeResponses = {
    /**
     * Successful Response
     */
    200: KnowledgeResponse;
};

export type UpdateKnowledgeResponse = UpdateKnowledgeResponses[keyof UpdateKnowledgeResponses];

export type RootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootResponses = {
    /**
     * Successful Response
     */
    200: RootResponse;
};

export type RootResponse2 = RootResponses[keyof RootResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type ClientOptions = {
    baseURL: `${string}://openapi.json` | (string & {});
};